### ISSUE TITLE
Problem with the timeout_after

### ISSUE THREAD

**Issue by cmyllis** [OctopusDeploy/await-task-action#22]
According to this...
![image](https://github.com/OctopusDeploy/await-task-action/assets/96247992/81e90878-135a-48b6-8100-cf082d33ee59)
...my understanding is that the default timeout if not set is 10 minutes.

I have created a combined action that runs a runbook and wait for it to finish.
I have seen workflows that run a lot more than 10 minutes and I dont see any timeout.

Am I missing something in how the behaviour should be? Is the timeout infinite if it is not set?

**Comment by jonagh** [comment]
I'm also trying to figure out why my `OctopusDeploy/await-task-action@v3` isn't timing-out appropriately.
I have `timeout_after: 1800` (30 min), but the job times out after 6 hours (which I believe is GitHub's own job timeout period).

Briefly looking at the code I see two funny things:

- The code seems to be pulling input `timeout` rather than `timeout_after`.
See: https://github.com/OctopusDeploy/await-task-action/blob/63eb58aa98227049045bb7a8d557d36add8e3b1e/src/input-parameters.ts#L46C16-L46C17

However that would just mean the custom value does not get used, and instead the default of 600s should be, but it's not.
So I kept looking...

- In ServerTaskWaiter (from dependency OctopusDeploy/api-client) the `waitForTasks` method creates a timeout (using `setTimeout`) which will run the callback to stop waiting after the given timeout period (as is desired)... but then in the wait loop there is a finally block which runs `clearTimeout` on that timeout, discarding the timeout immediately after the first loop 😮 
See: https://github.com/OctopusDeploy/api-client.ts/blob/1f265edb521f4e36df8aeeeedde5410e9cb98405/src/features/serverTasks/serverTaskWaiter.ts#L84
